### ISSUE TITLE
[FEAT] Adds support for second teacher of a class

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3610] opened 2022-11-09 16:47 UTC
**Description**
As requested it would be nice to add support for teachers to add a second teacher to their classes. It would however still be nice to make sure that only the "main" teacher can make crucial decisions like renaming, deleting and/or duplicating the class. We do have to "puzzle" a bit as the classes of a teacher are stored in the database as well as on the user profile. In this case we have to alter the profile itself as well.

Maybe we can use the user invite for class structure to implement this "invite as teacher" idea?

**Comment by Felienne** [comment] 2023-10-07 10:10
This could be a fin issue for @hasan-sh to get started with, since it will help get to know our teacher backend. There are a few things to consider though, I think we want to go for a "first teacher" and "second teacher" where maybe only the first teacher can, for example, delete the class, or remove students? And we have, of course, to think of interesting edge cases, what is a secondary teacher removes their account? What is a first teacher does this? So a bit of "scoping out" is needed before the start of this.

**Comment by hasan-sh** [comment] 2023-10-11 11:27
Since the "second teacher" may or may not have all capabilities, I'm thinking of the following user story:

The first teacher creates a _class_. They can create and customize classes, adventures, and add/invite/create students. Among the aforementioned things the teacher is able to control, they may add a second teacher (or a teacher assistent; since several may be added in the future!) with _certain capabilities_. The teacher assigns one of the following labels to their assistent: viewer (default), moderator, admin. 

A viewer can:
- [ ] view statistics; the progress of that class and students. 

A moderator (allowed to perform specific actions) can:
- [ ] view adventures, live stats and progress so far (explore)
- [ ] add/invite/remove students
- [ ] customize the class; add/remove/assign adventures
- [ ] @Felienne maybe there's more actions to be considered? But this is what I found after loging in as a teacher and playing around a bit!

> These actions, as you mentioned, should be specified by the teacher (so, ui needed).  
> I think the first two would be logical to be the default for the moderator, while the third is not and needs to be determined by the teacher. 

Finally, an admin is granted with all capabilities of the teacher (really second teacher!) 


In case a teacher removes their account, then I don't think we can do a lot other than transferring the ownership of their classes to the TAs with admin capabilities, iff the teacher agrees with that. I think this is an unlikely scenario, but it's still an option! Further, if the TA removes their account, then we can only inform the teacher about it. This can be done by either sending an email or leaving a notification in the related class(es) page(s). Also, all things created by the TA should still be available unless otherwise specified by the teacher; e.g., when the teacher removes the TA explicitly!

Another thing that's worth considering is tracking the actions of these users. This gives more transparency on who did what and when.

**Comment by hasan-sh** [comment] 2023-10-17 12:15
The idea can be expanded later to allow teachers assign roles to second teachers thereby introducing the notion of having a TA instead of a second teacher. For now, I'll implement the second teacher idea where they would have all permissions that the actual teachers have.

**Comment by hasan-sh** [comment] 2023-10-17 12:22
One thing that's worth noting is the following scenario:
- A second teacher is assigned to class X
- Class x uses y and z adventures.
- The seacond teacher tweaks adventure y.
- All other classes (e.g. class k) would be affected by it. 

The expected behavior is that the effect is only applied on classes where that have those second teachers, which is logical and more transparent. This will probably be more related when we work on `content management`.

**Closed** 2023-11-06 09:13 UTC
Labels: teachers
