### ISSUE TITLE
[CONTENT] is ask is not localized

### ISSUE THREAD

**Issue by spaanm** [hedyorg/hedy#4516] opened 2023-09-20 15:56 UTC
**Describe the issue**
What level, language and adventure does this concern?
Level 2, tab 'vraag'. In het Nederlands staat in het 2e voorbeeld 'is ask' in het Engels.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

<img width="1273" alt="Hedy" src="https://github.com/hedyorg/hedy/assets/13274422/808bfb6f-42cb-4480-b759-8a811043f077">

**Expected text**
What should we write instead?
 is vraag

**Comment by Felienne** [comment] 2023-09-20 18:18
Thanks @spaanm! We will take a look tomorrow!

**Comment by yilmazdurmaz** [comment] 2023-09-24 16:34
Internationalization is still not at its peak. There will be such issues until someone contributes to translations and corrects these hickups.

Yet, I must stress this: you can use both English keywords and keywords from your language in Hedy programs.

If you see a word turn into this reddish color, and have them in correct order, then Hedy will understand and run the program correctly. 

![mixed programming](https://github.com/hedyorg/hedy/assets/1812105/d0f93803-e308-4b68-9fe7-3e73be2edfc8)

@Felienne, is this an intentional design or a side effect? I don't remember translating anything about this, so it might be good to add some words about this into documentation.

**Comment by Felienne** [comment] 2023-09-24 17:26
> Internationalization is still not at its peak. There will be such issues until someone contributes to translations and corrects these hickups.

Yes, we are working on this as hard as we can.

> @Felienne, is this an intentional design or a side effect? I don't remember translating anything about this, so it might be good to add some words about this into documentation.

Yes, this is intentional (see f.e. my video in the Wiki) I think it is documented for teachers, but we could check

**Comment by yilmazdurmaz** [comment] 2023-09-25 12:50
@Felienne  I have searched the source material on Weblate for the words "mix" and "keyword". There are "program in English, and also in your own language" (I shortened in meaning), but none gives any clue about "you can mix a keyword's language (English and your own) provided you keep their position" or something like that.

**Comment by Felienne** [comment] 2023-09-26 11:05
> **Describe the issue** What level, language and adventure does this concern? Level 2, tab 'vraag'. In het Nederlands staat in het 2e voorbeeld 'is ask' in het Engels.
> 
> **Add a screenshot (optional)** Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.
> 
> <img alt="Hedy" width="1273" src="https://user-images.githubusercontent.com/13274422/269346039-808bfb6f-42cb-4480-b759-8a811043f077.png">
> **Expected text** What should we write instead? is vraag

Thanks again for letting us know @spaanm! As fas as I can see, this is correct in our texts, and I suspect this is a browser caching issue. It would be great if you could confirm that indeed after refreshing the page (or maybe after closing your browser and reopening it). If that is the issue, we can force a refresh after a switch of keywords. If that is not the issue, I will have to dive in more since I can't reproduce it.

**Comment by yilmazdurmaz** [comment] 2023-09-26 11:36
4 days ago, a Weblate contributor corrected the keywords (at least for this tab) so they are now in curly braces correctly.

**Comment by Felienne** [comment] 2023-09-26 12:19
Ah great, thanks for the clarification!

**Closed by Felienne** 2023-09-26 12:19 UTC
