### ISSUE TITLE
[BUG] Ask command with = and missing quote becomes a misleading assignment

### ISSUE THREAD

**Issue by ora-lv** [hedyorg/hedy#3727] opened 2022-11-28 14:40 UTC
**Describe the bug**
The sample code for Level 9 - Restaurant does not work anymore

**Paste the Hedy code & level**
Weird behavior in Level 9...
This code works:
people = ask 'How many people?'
repeat people times
    print 'Hello!'

But this code gives an error:
print 'Welcome to BYB ice cream parlor'
people = ask 'How many people want ice cream?
print 'We have the following sizes: kiddie, small, medium and large.'
price = 0
repeat people times
    size = ask 'What size would you like?'
    if size is kiddie
        price = price +3
    if size is small
        price = price + 4
    if size is medium
        price = price + 5
    if size is large
        price = price + 6
drinks = ask 'How many drinks would you like?'
price = drinks + price
print 'Thanks for your order! ' people ' ice creams are coming up!'
print ' That will be ' price '  please'

ERROR:
We can't run your program.

You cannot use repeat times with people because it is text. Try changing people to a number or input from {ask}.

**Comment by noelgolding** [comment] 2022-12-31 15:49
@ora-lv it seems to me the issue is a missing closing quote from 
`people = ask 'How many people want ice cream?`

**Comment by boryanagoncharenko** [comment] 2024-08-06 10:54
While it seems counter-intuitive, the type error is correct and expected. Up until level 11 we allow assigning a variable without using quotes (e.g. `a = I'm puzzled!` instead of `a = "I'm puzzled!"`). In the provided snippet, the definition of the variable `people` is meant to be input from the `ask` command. However, because 1) the `=` operator is used instead of `is` operator and 2) there is a missing closing quote, this becomes a valid variable assignment which just happens to start with the word `ask`. This is why the error message says that the `people` variable is interpreted text and not an input from the `ask` command.

Here is the minimal program that illustrates the issue:
<img width="1027" alt="Screenshot 2024-08-06 at 13 29 42" src="https://github.com/user-attachments/assets/7a6296a4-ba42-47b4-a8b3-7530e280c4ad">
```
people = ask 'How many people want ice cream?
print people
```

Note that if we change the `=` to an `is`, we get a missing quote error:
<img width="1022" alt="Screenshot 2024-08-06 at 13 30 13" src="https://github.com/user-attachments/assets/098e0e8a-89cb-4507-b85f-81d96a5455c5">
```
people is ask 'How many people want ice cream?
print people
```

Ideally, the error message should guide the user to the missing quotes. However, guessing the intention of the user to use the `ask` command in such cases is technically hard. Perhaps we could disallow using the `= ask` until level 12 when quotes are required in assignments? We could also migrate all examples to use `is ask`.

**Comment by Felienne** [comment] 2024-08-28 09:42
> We could also migrate all examples to use `is ask`.

I think this would be my preferred solution!

**Closed** 2024-09-03 01:06 UTC
Labels: bug, language
