### ISSUE TITLE
[BUG] Ask gives a runtime error in level 8 with repeat and text

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#2790] opened 2022-05-20 08:27 UTC
**Describe the bug**
Entering text with ask gives a runtime error in level 8 (and maybe more)

![image](https://user-images.githubusercontent.com/1003685/169487082-25638ad2-a9a8-41f1-a56d-936efa978370.png)

**Paste the Hedy code & level**
```
hoeveel is ask 'hoeveel?'
repeat hoeveel times
    print 'Hello everyone'
    print 'This is all repeated ' hoeveel ' times'
```

Enter f and get the error.

**Comment by ThomasKluiters** [comment] 2022-05-31 07:39
Hi @Felienne, you self-assigned this one, but I can pick this one up!

**Comment by Felienne** [comment] 2022-05-31 07:54
> Hi @Felienne, you self-assigned this one, but I can pick this one up! Are you currently working on it?

No, it would be lovely if you could pick this up since I will be traveling this week and next week!

**Comment by arjank** [comment] 2022-07-29 16:45
@Felienne could you verify that this issue no longer exists?

**Comment by Felienne** [comment] 2022-07-29 17:21
No I can't I am on vacation :)

But I closed the pr because it was too far behind, not because the issue
was fixed (I don't know if it is, you can probably copy paste and see for
yourself?)

**Comment by arjank** [comment] 2022-07-29 17:53
> No I can't I am on vacation :) But I closed the pr because it was too far behind, not because the issue was fixed (I don't know if it is, you can probably copy paste and see for yourself?)

Enjoy your vacation!

The reason I asked was because I failed to reproduce it myself ;)

**Comment by boryanagoncharenko** [comment] 2022-07-30 19:31
> The reason I asked was because I failed to reproduce it myself ;)

Not sure if this helps, but I was able to replicate it both locally (using the latest changes in main) and on hedycode.com. The repeat statement gets transpiled to `for i in range(int(hoeveel)):` and if you make the hoeveel a non-int value (e.g. 'f'), you will get this unfriendly error.

We could address this problem in the transpiler like we have done in the past. However, this is not nice because the error text is literally hardcoded in English in the transpiler. I am wondering whether we could have a more general approach for displaying friendly errors caused by incorrect type of input and also translate them to the right language.

**Comment by Felienne** [comment] 2024-01-26 16:12
Hi @boryanagoncharenko!

Another one for you maybe? We now have nicer, translated, run-time errors that we generate in a try-catch. Let me know if you need help figuring the new system out!

**Closed** 2024-02-19 16:21 UTC
Labels: language
