### ISSUE TITLE
[BUG] Code in slides not rendered, also achievements mustn't show

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4895] opened 2023-12-12 13:46 UTC
**Describe the bug**
The code is not show in editor unless you run it, see the following ss:

![image](https://github.com/hedyorg/hedy/assets/20051470/dc003eb2-d70e-4952-b27f-d71c8df8aa09)

Although the code is not shown here, it is visible within the Speaker view: 

![image](https://github.com/hedyorg/hedy/assets/20051470/de21f3aa-4f26-43ae-b33d-506df0fbd816)

**Achievements** should not be granted when viewing the slides:

![image](https://github.com/hedyorg/hedy/assets/20051470/77c523bc-003a-41c4-bfbb-d6ffe3665f3f)

**Comment by Felienne** [comment] 2023-12-12 14:32
Good find, very interesting weird bug! It is not always the case, somehow:

<img width="1207" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/9320f2d4-e9db-4fef-952f-2c5f38111ceb">

And a refresh seems to fix it?

Will you dive in or are you working on other things?

**Comment by Felienne** [comment] 2023-12-20 12:14
Hi @hasan-sh!

I think this is closed by #4915 The achievement issue, I suspect, was due to the css issue, but I am not 100% sure to reproduce it, so I will leave it to you to close it!

**Closed** 2023-12-20 12:52 UTC
