### ISSUE TITLE
🪲Variable not defined while defined

### ISSUE THREAD

**Issue by hakkas** [hedyorg/hedy#5974] opened 2024-11-26 08:48 UTC
**Describe the bug**
While executing the code I get a "variable price not defined" error.

**Paste the Hedy code & level**

_This bug occurs in level 8_
print 'HedyWheels bus tickets machine'
zone_1 = Town Hall, Library, Campus, Market Place
zone_2 = Swimming Pool, Skate Park, Mall, Airport
destination = ask 'Where do you want to go?'
if destination in zone_1
    print destination ' is in zone 1'
    price = 3
if destination in zone_2
    print destination ' is in zone 2'
    price = 6
ticket_types = ask 'Press 1 for a single use ticket. Press 2 for a round trip ticket:'
if ticket_types = 1
    print 'You chose a single use ticket'
else
    print 'You chose a round trip ticket'
    price = price * 2
print 'That will be ' price ' euros please'

**Comment by Felienne** [comment] 2024-11-26 17:21
Hi @boryanagoncharenko!

Do you have time to pick this one up?

**Comment by boryanagoncharenko** [comment] 2024-11-27 12:49
@hakkas thank you for reporting this issue.

Since the code you pasted is not formatted (and is missing indentation), would you be able to confirm that the following snippet matches your code:
```
print 'HedyWheels bus tickets machine'
zone_1 = Town Hall, Library, Campus, Market Place
zone_2 = Swimming Pool, Skate Park, Mall, Airport
destination = ask 'Where do you want to go?'
if destination in zone_1
    print destination ' is in zone 1'
    price = 3
if destination in zone_2
    print destination ' is in zone 2'
    price = 6

ticket_types = ask 'Press 1 for a single use ticket. Press 2 for a round trip ticket:'
if ticket_types = 1
    print 'You chose a single use ticket'
else
    print 'You chose a round trip ticket'
    price = price * 2
print 'That will be ' price ' euros please'
```

If the code snippet is correct, then it seems that it is working correctly if the input I provide is an element in the lists zone_1 or zone_2. Here is the output if I provide `Mall` to the first input inquiry and `2` to the second one:
<img width="1114" alt="Screenshot 2024-11-27 at 13 40 31" src="https://github.com/user-attachments/assets/ecf05883-2562-4b02-beb4-3f4df2c7e573">

The only way I am able to get a "name 'price' not defined" error is if I provide input which is not in the zone_1 or zone_2 lists, e.g. `mall` or `Home`. This is how it looks:
<img width="1114" alt="Screenshot 2024-11-27 at 13 38 30" src="https://github.com/user-attachments/assets/948a5ac2-c822-40da-8e48-4a094e1155ff">

Is this the correct way to reproduce the error you get on your side? If so, there are multiple aspects to consider.

1. Is the error a bug?

Note that the `price` variable is defined only if the input of the user is within the elements of zone_1 or zone_2. If the input is not in these lists, then the lines setting the price to 3 or 6 would not be executed and the final print statement will know nothing of a `price` variable. In other words, the `price` variable not is defined in all possible program execution paths which means the error is yielded correctly.

2. How to correct the program in the context of Hedy?

In level 8, the easiest way to avoid the error is by setting an initial price value of 0:
```
print 'HedyWheels bus tickets machine'
zone_1 = Town Hall, Library, Campus, Market Place
zone_2 = Swimming Pool, Skate Park, Mall, Airport
destination = ask 'Where do you want to go?'
price = 0  # Initialize the price to 0
if destination in zone_1
    print destination ' is in zone 1'
    price = 3
if destination in zone_2
    print destination ' is in zone 2'
    price = 6
...
```

However, this solution is not nice because now the program will proceed to ask whether it is a single or a round trip journey even though the destination is unknown. Unfortunately, there is not an easy way to avoid this in level 8. However, in level 9 we can have nested if-else statements. So we could adapt the program to halt if the destination is unknown:
```
# level 9
print 'HedyWheels bus tickets machine'
all_destinations = Town Hall, Library, Campus, Market Place, Swimming Pool, Skate Park, Mall, Airport
zone_1 = Town Hall, Library, Campus, Market Place
zone_2 = Swimming Pool, Skate Park, Mall, Airport
destination = ask 'Where do you want to go?'

if destination not in all_destinations
    print destination ' is an unknown destination. Try again!'
else
    if destination in zone_1
        print destination ' is in zone 1'
        price = 3
    if destination in zone_2
        print destination ' is in zone 2'
        price = 6

    ticket_types = ask 'Press 1 for a single use ticket. Press 2 for a round trip ticket:'
    if ticket_types = 1
        print 'You chose a single use ticket'
    else
        print 'You chose a round trip ticket'
        price = price * 2
    print 'That will be ' price ' euros please'
```

3. Why is the error message not user-friendly?

The specific error message displayed is `Something went wrong while running the program. name 'price' is not defined` which is not very helpful or inline with the other error messages in Hedy. For example, there is no line in which the error occurs. The reason is that this is an error coming from the python code in the Skulpt execution. It is technically very hard to track this error in Hedy at compile-time. So there are two options:

3.1. One option is to prepend a NameError check before every variable access. For example:
```
try:
    price
except NameError as e:
    raise NiceHedyError(`price`, meta.line)
print 'That will be ' price ' euros please'
```
However, this might be practically impossible because variables could be heavily nested in other statements, e.g. expressions. Additionally, the effort might outweigh the benefits because the error does not occur very often.

3.2. Another way to improve the error is by catching the error produced by Skulpt and amending it with the line number provided by the python exception. However, note that the line number in the transpiled python could differ significantly from the line number in the Hedy program. This would require further investigation, so I will link this to #4770 as a point for consideration.

**Comment by hakkas** [comment] 2024-12-02 21:50
Hi @boryanagoncharenko ,

Thank you for the detailed response. I'm not sure why, but it seems to be working now. The indented code you provided is exactly the same as what I tested. Actually, one of my students encountered this error, and I couldn't figure out why it wasn't working. I now understand that the variable `price` wouldn't be defined if the destination isn't in zone_1 or zone_2. The issue, however, was that the code didn't run at all and just gave me the error message.

**Comment by boryanagoncharenko** [comment] 2024-12-03 07:21
Hi @hakkas ,

Thank you for the details. So, the error you received appeared immediately after you execute the program, without the ask command prompt appearing at all? Do you remember how exactly the error looked like? Was is like this:
<img width="734" alt="Screenshot 2024-12-03 at 9 12 37" src="https://github.com/user-attachments/assets/d5cc0467-3c2a-47b0-a4d0-9bda99e55ea9">
Or did it look like this:
<img width="737" alt="Screenshot 2024-12-03 at 9 12 21" src="https://github.com/user-attachments/assets/d71b3e3b-0101-4b4c-a967-6c8e8c5baae8">
Or was it a different error?

Also, do you know in what time frame were you getting this error? If I have the time, I might be able to get more information from the logs. Thanks!

**Comment by boryanagoncharenko** [comment] 2024-12-20 11:16
I am closing this issue for now. If the problem resurfaces, please reopen this issue. We would appreciate if you can paste the exact error message or upload a screenshot of the failure.

**Closed by boryanagoncharenko** 2024-12-20 11:16 UTC
Labels: bug
