### ISSUE TITLE
[UI idea] Localized keywords in the teacher manual

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4134] opened 2023-03-16 11:38 UTC
The teacher manual doesn't use localized keywords, only the English ones. It would be nice if the keywords could change to the preferred language setting of the teacher. I mainly mean in the common mistakes section. 

I've tried to just use the { } around the keywords, but that didn't do the trick.

**Comment by yilmazdurmaz** [comment] 2023-09-23 13:37
We have curlies for half of the translation for both the text and the code. But unfortunately, they do not work the way we translators expected them.

This resulted in this Frankenstein's monster
![teachers manual](https://github.com/hedyorg/hedy/assets/1812105/6128a2d2-4dfc-4b60-ab16-bafe4b953883)

**Comment by yilmazdurmaz** [comment] 2023-09-29 15:30
By the way, the common mistakes content would also be very useful to all students, especially to self-learners. Moving that section to its own page with visibility to all students may not only help all learners, but also help this keyword translation process.
Worth to consider later, but maybe before working on that page all together.

PS: This is a duplicate of my sentence in the other issue I mentioned about this, for this mainly belongs there.

**Closed** 2024-08-05 19:35 UTC
Labels: teacher-happiness
