### ISSUE TITLE
[BUG] Arabic code editor incorrectly editing text when using text selection with backspace and/or delete 

### ISSUE THREAD

**Issue by alaaeddin-swidan** [hedyorg/hedy#3823] opened 2022-12-09 11:52 UTC
**Describe the bug**
When editing code in the Arabic language: specifically trying to change some text using simple text selection with the backspace and delete buttons, it is then impossible to determine where the cursor is going to take the action and therefore the editing of the textual code is hindered. 

**Paste the Hedy code & level**
Applies to all levels. But let's take the following as an example: Level 2 -> introduction -> first example code: 
الاسم هو هيدي
العمر هو ١٥
قول الاسم وعمرها الان العمر سنة

**Video screen comparing Arabic and English code 

https://user-images.githubusercontent.com/7933089/206694714-1fcc8e7a-5a43-4261-87f8-fc6a28e38709.mp4

The actions above show that a shift is happening to the left whenever a selection is done on a letter or a word, the first operations were a backspace: what they do is they remove a character ahead (left of the selection by 2 spaces (I think)) rather than going backward to the right while deleting the character.. Another one is when selecting the whole word الان followed by a backspace: the word itself stays as is (not deleted) but the deletion happens also somewhere to the left (ahead of the word).

https://user-images.githubusercontent.com/7933089/206694752-c3d5e114-9515-4db5-84d1-68a045de744e.mp4

In the English editor the actions are as expected. 

**What machine and browser you were using (optional)**
Windows. Firefox browser.

**Comment by Felienne** [comment] 2022-12-09 16:20
Hi @alaaeddin-swidan!

Is this a new issue (in my experience this has always been the case) Just trying to understand if this is something we broke or that is most likely in Ace.

**Comment by vzsky** [comment] 2023-02-12 08:08
I'm not sure whether the arabic one is the same as this case. But with Thai, AceAjax edit seems not to fully support the language. 

for example, try the word "คำที่มีปัญหา" in the official(?) ace editor [here](https://ace.c9.io). When you move the cursor to the back of the word, it extends beyond the actual position of the end of the visual word as there are 0 length characters.

I suspect something with this issue on ace : https://github.com/ajaxorg/ace/issues/4512 
Or this one in the case of arabic? : https://github.com/ajaxorg/ace/issues/460

In the past, I had used [codemirror](https://codemirror.net), where there were no problem with Thai. But still have no up-to-date information.

**Comment by alaaeddin-swidan** [comment] 2023-03-06 16:03
Hi @Felienne no this is not a new issue. 
Thanks for the input @vzsky. I tried the official Ace edi


tor, the problem shows also there. There seem to be a 10 character shift to the left, this is evident from their text-input-debugger window - i show here another screen video of the issue. 
I will investigate further whether a solution exists somehow. 

https://user-images.githubusercontent.com/7933089/223164140-733c29d9-d78f-4109-b632-e389126ac00f.mp4

**Comment by Felienne** [comment] 2023-03-06 16:25
I understand this is very annoying, but at a first glance this seems to be out of our control. We might be able to patch it with some CSS as we have in other cases, but if this is an issue in Ace it will be hard to fix (other then from submitting an issue and maybe a PR to Ace).

Or, as suggested, we can fix it by swapping out the entire editor to CodeMirror. That is a thing we have considered before but of course that'd be a large project that we do not start lightly.

So hopefully you will find an issue in Ace with some setting or other, otherwise this will probably stay on the log for a while.

**Comment by Felienne** [comment] 2023-03-07 08:47
In https://github.com/ajaxorg/ace/issues/2548 someone mentions this could be fixed by using a " fixed width font". I am not sure we have to for Arabic or Thai (or whether that even exists?) but it could be worth a try. Diving into https://github.com/ajaxorg/ace/issues/2548 and its many (many!) duplicates might be a good start:

Some things to try:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/1003685/223370587-d9788e1a-9461-4106-96a9-f5f569f5a177.png">

**Comment by Felienne** [comment] 2023-03-07 08:48
The problem is that it is hard for me to try since I don't really know what success/failure looks like.

**Comment by reedspool** [comment] 2023-04-09 09:18
Took a look at this. I think if #4090 doesn't get this to a suitable place, then I think the only reasonable alternative is moving to CodeMirror. I know this is a big project so I wouldn't vote that way lightly.

First, to explain the issue concisely, read the first post of [this issue from 2013]( https://github.com/ajaxorg/ace/issues/1429#issue-14307352), 10 years ago.

Then later, in 2016, [tomerm explains exactly why this is a fundamental flaw in Ace](https://github.com/ajaxorg/ace/issues/1429#issuecomment-236827290)

The short version is that Ace uses a bespoke text rendering engine, and it's apparently been western-text-focused for over 10 years. All these issues you've collected show a major lack of support from the primary contributor, nightwing. The issues generally trail off into "does anyone have a fix for this?" with no supportive replies. More than one of the threads I read mentioned this exact issue being a deciding factor for moving to CodeMirror. 

So, either Ace already supports this, and it should be as easy as getting the CSS/font choice right, or the support is not there and it might be another decade before Ace gets it right.

**Comment by Felienne** [comment] 2023-06-27 17:42
We are going to (ultimately) replace Ace with CodeMirror (see: #4339) so this specific issue will be addressed but it might take a while.

**Comment by Felienne** [comment] 2023-09-25 14:36
Update: https://github.com/hedyorg/hedy/pull/4479 will fix this (hopefully) so this can be removed from our working list.

**Comment by vzsky** [comment] 2023-11-27 16:03
Thanks a lot for the improvement. Although I am not sure if its work correctly in arabic, I have tested that it is now perfectly working in Thai, unlike earlier with aceajax.

**Comment by jpelay** [comment] 2023-12-18 23:37
@Felienne can we close this one?

**Comment by Felienne** [comment] 2023-12-19 06:18
Yes I think so! I have not heard back from https://github.com/alaaeddin-swidan but it seems to work for other languages with issues!

**Closed by Felienne** 2023-12-19 06:19 UTC
Labels: localization
