### ISSUE TITLE
[BUG] language switcher switches back

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#4579] opened 2023-10-02 17:03 UTC
If the preferred _commando_ language is English and the url is similar to this: https://hedycode.com/hedy#default (it happens in every level) the language switchers is switched to English. If I then use the language switcher to switch to Dutch (the preferred _language_), the switcher switches back to English at once and the url changes to: https://hedycode.com/hedy?keyword_language=en#default . From this point on the switcher works as intended.

**Comment by Felienne** [comment] 2023-10-17 18:33
This might also be a nice front-end fix for @hasan-sh? (Like the drop downs that don't close)

**Comment by Felienne** [comment] 2023-10-18 08:40
HI @AnneliesVlaar! 

Me and @hasan-sh are looking into this issue, and I know you showed the issue in the previous meeting, but I can't remember how to reproduce it and from the description we can't figure it out. Would you mind explaining it in a bit more detail or recording a video?

I think our confusion starts with "If the preferred commando language is English ... the language switchers is switched to English. " because if your preferred commando language is English, there is no switcher?

Thanks!!

**Comment by yilmazdurmaz** [comment] 2023-10-18 09:20
to reproduce:
- in "my account", open "my personal settings"
- change "Preferred language" to something other than English
- set "Preferred keyword language" to English
- switch to adventures (Hedy) and URL gets to be `{host}/hedy#default`
- open language switcher, swtich language, URL becomes `/hedy?keyword_language=en#default`
  - the first time you do this, it still stays being English
  - you have to hit the switcher a second time

whenever you visit other pages while the keyword language is last set to English, then this repeats: you have to hit twice to actually switch the keyword language.

**Comment by AnneliesVlaar** [comment] 2023-10-18 10:06
Hi @Felienne ,

The bug is only working in specific conditions ;-) Here is a screenrecording:

https://github.com/hedyorg/hedy/assets/66774020/4e88bfbd-5f98-4af1-a939-ae9c2ba4da4c

**Comment by hasan-sh** [comment] 2023-10-19 04:44
Thanks @AnneliesVlaar and @yilmazdurmaz for clarifying the issue. It should be fixed by #4647 :)

**Closed** 2023-10-20 11:12 UTC
