### ISSUE TITLE
Command ‘at random’ on an empty list gives a student an unfriendly exception

### ISSUE THREAD

**Issue by ericverschoor** [hedyorg/hedy#1919] opened 2022-02-06 20:51 UTC
Given the following program at level 3

    lijstje is wouter, eric
    remove wouter from lijstje
    remove eric from lijstje
    print lijstje at random

when executing *at random* at an empty list, an ‘child’ unfriendly exception ‘list index out of range’ is thrown

IMHO a student at level 3 should not have to be aware of the constraints when using an empty array.

![4B4DBE94-A04B-4EFF-B905-52C3DBC47246](https://user-images.githubusercontent.com/45706519/152700779-f7b68e55-fa56-4279-aabc-9e8a688e7fee.jpeg)

**Comment by Felienne** [comment] 2022-02-07 08:30
AH yes that is a Python error that is leaking out and that indeed is not friendly!

**Comment by Felienne** [comment] 2022-02-07 08:30
But because it is a run time error this will not be easy to fix (but I will try of course!)

**Comment by Felienne** [comment] 2022-02-08 13:35
Duplicate of #1699 but this is more extensive so I am keeping this one

**Comment by Felienne** [comment] 2022-04-12 05:47
Maybe this one @erinshi?

**Comment by erinrshi** [comment] 2022-04-12 06:12
@Felienne thank you i can work on this! 
what is the expected output supposed to be in this case? should it not display any error message and just have no output?

**Comment by Felienne** [comment] 2022-04-12 06:32
Yes, we want the Python error to not leak out, but no error message is not friendly either. I would love a message like: "warning, lijstje is empty" but that might be hard to create?

**Comment by erinrshi** [comment] 2022-04-13 01:56
hi @Felienne, I've looked at the code and tried a couple of ideas, but am unable to change the error message. I see it's coming from the skulpt.min.js which I'm not supposed to change. 
Do you know where in the code actually runs the underlying Python code and throws the error?


<img width="451" alt="Screen Shot 2022-04-12 at 9 55 22 PM" src="https://user-images.githubusercontent.com/70287578/163084128-883f7c50-4ae5-44a9-8436-0bb014829775.png">

**Comment by Felienne** [comment] 2022-04-13 07:04
> hi @Felienne, I've looked at the code and tried a couple of ideas, but am unable to change the error message. I see it's coming from the skulpt.min.js which I'm not supposed to change. Do you know where in the code actually runs the underlying Python code and throws the error?
> 
> <img alt="Screen Shot 2022-04-12 at 9 55 22 PM" width="451" src="https://user-images.githubusercontent.com/70287578/163084128-883f7c50-4ae5-44a9-8436-0bb014829775.png">

I am not all too familiar with Skulpt's internals either, but it seems we are able to catch certain exceptions:

https://github.com/skulpt/skulpt/issues/214

That would be done in the typescript code, not in the `skulpt.min.js` which indeed we should not adapt.

**Comment by sfayyad** [comment] 2022-11-10 07:24
Hi! I would love to work on this task to gain more open-source experience with back-end development!

**Comment by jpelay** [comment] 2024-03-12 16:36
This issue has been solved already:
![image](https://github.com/hedyorg/hedy/assets/45865185/187b2347-ac9a-47b6-8989-5ee74a5b53df)

**Closed by jpelay** 2024-03-12 16:36 UTC
Labels: level3, error messages, language, approved
