### ISSUE TITLE
[BUG] Comments at indented code-block not allowed.

### ISSUE THREAD

**Issue by eremmel** [hedyorg/hedy#3287] opened 2022-09-16 13:35 UTC
**Describe the bug**
When you want to use comments in indented code section it is not allowed. Compiler gives a weird message.

**Paste the Hedy code & level**
Levels tested with this code: 8, 11 and 18
![image](https://user-images.githubusercontent.com/1874108/190646600-74d66208-baf7-47f3-820b-8a23e91e403f.png)

**Add a screenshot (optional)**
Error reported is all cases is:
![image](https://user-images.githubusercontent.com/1874108/190647023-273fb125-5077-43fd-b177-8912eaa9a1e3.png)

**Expected behavior**
Indented comments are allowed and does not impact program.

**What machine and browser you were using (optional)**
N/A Error is generated by backend server

**Comment by eremmel** [comment] 2022-10-15 19:13
Here some more comment issues. After the update of Hedy some code at level 10 did not run any more due to fact that whitespace before comment token '#' is not considered. At level 10 any way strings needs quotes!
![image](https://user-images.githubusercontent.com/1874108/196004057-31452656-95ce-4d9f-829e-0e5d540a8201.png)

**Comment by arjank** [comment] 2022-10-16 21:58
At level 10 you do not need quotes for string assignments. That is only as of level 12.

But there are also issues at level 12:
![image](https://user-images.githubusercontent.com/457006/196060107-5286f40d-9dd0-468e-9483-d340aa4ea3e0.png)

And the code, for easy reference.
```
i = 4   # met comment
print '[' i ']'
if i = 4
    j = 4    # met comment
    print '[' j ']'
    if j = 4
        print 'comments ok on level 1'
    else
        print 'comments not ok on level 1'
else
    print 'comments not ok on level 0'
```
This code runs on levels 10 and 11 (though with incorrect output) and, as shown above, does not run at level 12.

**Comment by eremmel** [comment] 2022-10-17 06:48
Looks like the definition and implementation of comment starts with '#' i.s.o. regexp: \s*#.*$ (this regexp does not consider # in quoted strings).

**Comment by KavyaManocha** [comment] 2022-11-12 15:06
Hi, would I be able to be assigned to this issue ?

**Comment by boryanagoncharenko** [comment] 2024-08-05 13:29
This issue deserves a summary. Here is a list of all issues mentioned so far plus a couple of new issues which are tightly coupled to the old ones:

1. Indented comments (which appear in the bodies of commands such as `if` and `repeat`) are not allowed in all levels. For example:
```
repeat 3 times
    # comment
    print ‘3’
```
Resolution: this is a bug and will be addressed

2. Comments cannot appear at the end of indented commands in all levels. For example:
```
repeat 3 times
    print '3' # comment
```
Resolution: this is a bug and will be addressed

3. In levels 4-11 when a variable is assigned a quoted string containing #, its value is printed only until the # sign. For example in level 11 the following program:
```
a is 'this is a # test'
print a
```
outputs `'this is a`
Resolution: this is not a bug but the expected behavior of Hedy. In levels 4-11 only the `print` and `ask` commands require quotes. The assign command does not, which means the single quotes do not take precedence over the comment. Therefore, the variable value is indeed `'this is a`.

4. An issue which has not been mentioned but is tightly coupled to issue 3. is that printing a quoted string containing a # is not supported in all levels. In level 4, due to grammar ambiguity, the program would sometimes work. However, in all consecutive levels, it yields an error:
```
print 'comments start with the # sign'
```
Resolution: This is a bug and will be addressed

 5. Trailing spaces are not allowed in equality comparisons in level 12 and up. For example:
```
# add trailing space to the end of line 2
naam is 'James'
if naam is 'trailing space’
    print 'shaken'
```
Resolution: this is a bug and will be addressed

6. In levels 2-11 the assign command will inconsistently add to the value all trailing spaces. This this is an interesting problem that touches upon language design choices, I created a separate issue: #5684.

7. The equality command removes spaces in levels 8-11. For example:
```
i = this   is   # met comment
print '[' i ']'
if i = ‘this   is’
  print i
```
The above command will not print anything because right-hand-side of the `if` statement is transpiled to `this is` instead of `this   is`.
Resolution: this is a bug and will be addressed

**Closed** 2024-08-06 17:14 UTC
Labels: language
