### ISSUE TITLE
🪲Teacher page: adventures fold out below classes

### ISSUE THREAD

**Issue by rix0rrr** [hedyorg/hedy#5986] opened 2024-11-30 21:23 UTC
# What's the issue?

If you click the "Show classes" button first and then the "Show adventures" button, the adventures appear below the classes.

This is confusing if you have a lot of classes: it looks like the "Show adventures" button didn't do anything:

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/188623bb-0346-4756-b886-27d6f4ed8798">

# What's the solution?

The content probably shouldn't fold out in the middle of the tiles; those links should just go to a different page, but that's design that should be done.

# Next steps

Someone needs to redesign how this works.

**Comment by Felienne** [comment] 2024-12-01 06:41
This is actually a duplicate of #5967 (forgot I made that one, sorry!)

**Comment by boryanagoncharenko** [comment] 2024-12-04 09:10
I have bumped into this issue multiple times and I'd love to solve it!

My UI design skills are limited, so I could reorganize the components on the page to "stop the bleeding". However, if we have a designer who can plan a better solution altogether, perhaps I could wait and pick up the implementation of that design. Btw please note that adding a new page might make things worse if we don't have the other pages (adventure/class) adapted.

Let me know :)

**Comment by rix0rrr** [comment] 2024-12-04 09:18
How about we do the auto-closing folds as the resolution of #5967, and keep this ticket open for a larger redesign?

**Comment by rix0rrr** [comment] 2024-12-04 09:32
Honestly also close this one at the same time, we will address larger work as part of #5998

**Comment by boryanagoncharenko** [comment] 2024-12-04 09:38
So, final summation:
 - this is identical to #5967 and is only about stopping the bleeding
 - the big picture for teacher's experience is #5998 

If so, I will close this one, assign #5967 to myself and keep an eye on #5998

**Comment by boryanagoncharenko** [comment] 2024-12-04 11:45
Closing in favor of #5967 5967

**Closed by boryanagoncharenko** 2024-12-04 11:45 UTC
Labels: bug, teacher-happiness
